name: Python CI/CD Pipeline Template

# Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository Name'
        required: true
      deploy_env:
        description: 'Deployment Environment'
        required: true
      build_artifacts:
        description: 'Build Artifacts (true/false)'
        required: true
      python_version:
        description: 'Python Version'
        required: true

# Environment Variables

env:
  REPO_NAME: ${{ github.event.inputs.repo_name }}
  DEPLOY_ENV: ${{ github.event.inputs.deploy_env }}
  BUILD_ARTIFACTS: ${{ github.event.inputs.build_artifacts }}
  PYTHON_VERSION: ${{ github.event.inputs.python_version }}
  VERSION: ${{ github.sha }} # Use Git commit SHA for versioning

jobs:
  source_checkout:
    name: Source Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

# pytesting

  run_tests:
    name: Run Tests with Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Run Tests with Pytest
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Generate Test Report
        run: pytest --junitxml=junit/test-results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-${{ env.VERSION }}
          path: junit/test-results.xml

# SonarQube Code Quality Analysis And Vulnerability Scanning

  sonarqube_analysis:
    name: SonarQube Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SonarQube Scanner
        run: |
          curl -sSL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip -o sonar-scanner.zip
          unzip sonar-scanner.zip -d $HOME
          echo "export PATH=$HOME/sonar-scanner-4.8.0.2856-linux/bin:\$PATH" >> $GITHUB_ENV

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=${{ env.REPO_NAME }} \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN

      - name: Upload SonarQube Report (Optional)
        uses: actions/upload-artifact@v2
        with:
          name: sonar-report-${{ env.VERSION }}
          path: sonar-report.json

# Managing Artifact

  build_artifacts:
    name: Build Project Artifacts
    runs-on: ubuntu-latest
    if: ${{ env.BUILD_ARTIFACTS == 'true' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Artifacts
        run: python setup.py sdist bdist_wheel

      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ env.VERSION }}
          path: dist/

# Building Container Images

  build_container_image:
    name: Build Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ env.REPO_NAME }}:${{ env.VERSION }} .
          docker tag ${{ env.REPO_NAME }}:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.VERSION }}

      - name: Push Docker Image to Registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.VERSION }}

# Generating Swagger

  swagger_generate:
    name: Generate Swagger Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Swagger Tools
        run: |
          pip install flask-swagger
          # Additional setup for swagger if needed

      - name: Generate Swagger Documentation
        run: |
          python generate_swagger.py  # Assuming you have a script to generate swagger docs

      - name: Upload Swagger Documentation
        uses: actions/upload-artifact@v2
        with:
          name: swagger-docs-${{ env.VERSION }}
          path: swagger/

# Deployment

  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    needs: [build_artifacts, build_container_image, swagger_generate]
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying application version ${{ env.VERSION }} to ${{ env.DEPLOY_ENV }}"
