name: React Reusable CI/CD Pipeline

on:
  workflow_call:
    inputs:
      aws-access-key-id:
        description: 'AWS Access Key ID'
        required: true
        type: string
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true
        type: string
      sonarqube-token:
        description: 'SonarQube Token'
        required: true
        type: string
      sonar-project-key:
        description: 'SonarQube Project Key'
        required: true
        type: string
      sonar-organization:
        description: 'SonarQube Organization'
        required: true
        type: string
      aws-region:
        description: 'AWS Region'
        required: true
        type: string
      aws-domain:
        description: 'AWS CodeArtifact Domain'
        required: true
        type: string
      aws-domain-owner:
        description: 'AWS CodeArtifact Domain Owner'
        required: true
        type: string
      npm-repository:
        description: 'NPM Repository Name'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID for AWS Credentials'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key for AWS Credentials'
        required: true
      SONAR_TOKEN:
        description: 'SonarQube Token for Scans'
        required: true

jobs:
  build-test-sonar:
    name: Build, Test, and SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test -- --watchAll=false

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1.10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.sonar-project-key }}
            -Dsonar.organization=${{ inputs.sonar-organization }}
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions="**/*.test.js"
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarcloud-quality-gate-action@v1

  artifact:
    name: Build React App and Save Artifact
    runs-on: ubuntu-latest
    needs: build-test-sonar

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to AWS CodeArtifact
        run: |
          aws codeartifact login \
            --tool npm \
            --repository ${{ inputs.npm-repository }} \
            --domain ${{ inputs.aws-domain }} \
            --domain-owner ${{ inputs.aws-domain-owner }}

      - name: Save Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-app-build
          path: build/

  docker:
    name: Docker Build and Deploy
    runs-on: ubuntu-latest
    needs: artifact

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: react-app-build

      - name: Build Docker Image
        run: docker build -t react-app:latest .

      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name react-app react-app:latest
