name: React Reusable CI/CD Pipeline

on:
  push:
    branches:
      - feature/react-app # Adjust to your branch name
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SONAR_TOKEN:
        required: true
      MY_GITHUB_TOKEN:
        required: true
    inputs:
      aws-region:
        description: 'AWS Region'
        required: true
        type: string
      sonar-project-key:
        description: 'SonarQube Project Key'
        required: true
        type: string
      aws-domain:
        description: 'AWS CodeArtifact Domain'
        required: true
        type: string
      aws-domain-owner:
        description: 'AWS CodeArtifact Domain Owner'
        required: true
        type: string
      npm-repository:
        description: 'NPM Repository Name'
        required: true
        type: string
      ecr-repo-name:
        description: 'ECR Repository Name'
        required: true
        type: string

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install
          npm audit fix || true

      - name: Run Unit Tests with Jest
        run: npm test -- --watchAll=false --coverage --forceExit

  build-publish-deploy:
    name: Build, Publish, and Deploy Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check for Uncommitted Changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "uncommitted_changes=true" >> $GITHUB_ENV
          else
            echo "uncommitted_changes=false" >> $GITHUB_ENV
          fi

      - name: Configure Git User
        if: env.uncommitted_changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Increment Version
        if: env.uncommitted_changes == 'true'
        run: |
          npm version patch
          git add package.json package-lock.json
          git commit -m "Bump version [skip ci]"
          git push origin HEAD

      - name: Build React App
        if: env.uncommitted_changes == 'true'
        run: npm run build

      - name: Configure AWS Credentials
        if: env.uncommitted_changes == 'true'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to AWS CodeArtifact
        if: env.uncommitted_changes == 'true'
        run: |
          aws codeartifact login \
            --tool npm \
            --repository ${{ inputs.npm-repository }} \
            --domain ${{ inputs.aws-domain }} \
            --domain-owner ${{ inputs.aws-domain-owner }}

      - name: Publish Package
        if: env.uncommitted_changes == 'true'
        run: npm publish

      - name: Upload Package Artifact to GitHub
        if: env.uncommitted_changes == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: react-package
          path: ./build/
